version: 2.1

jobs:
  python_lint:
    docker:
      - image: evanfabry/python-terraform:circleci
    steps:
      - checkout
      - run:
          name: run black
          command: black --version && black --check --diff .
      - run:
          name: run isort
          command: |
            isort --check-only --diff ./

workflows:
  main:
    jobs:
      - python_lint
